include: package:lints/recommended.yaml

analyzer:
  language:
    strict-casts: false
    strict-inference: false
    strict-raw-types: false
  errors:
    overridden_fields: ignore

linter:
  rules:
    - camel_case_types
    - cancel_subscriptions
    - test_types_in_equals