name: kitsumon
description: A fox-powered content discovery platform that helps tracking anime and manga. A clean Dart wrapper for Kitsu.io / kitsu.app.
version: 0.2.0
homepage: https://github.com/Nebulino/Kitsumon/
issue_tracker: https://github.com/Nebulino/Kitsumon/issues

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  dio: ^5.7.0
  crypto: ^3.0.6
  json_annotation: ^4.9.0
  meta: ^1.15.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.25.8
  json_serializable: ^6.8.2
  build_runner: ^2.4.13
