name: kitsumon
description: A fox-powered content discovery platform that helps tracking anime and manga.
  Just a simple Wrapper for Kitsu.io.
version: 0.0.2
homepage: https://github.com/Nebulino/Kitsumon/
issue_tracker: https://github.com/Nebulino/Kitsumon/issues

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  dio: ^3.0.9
  crypto: ^2.1.4

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.2
  json_serializable: ^3.3.0
  build_runner: ^1.8.0